use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum UiComponentId {
    Accordion,
    Alert,
    AlertDialog,
    AspectRatio,
    Attachment,
    Avatar,
    Badge,
    Breadcrumb,
    Bubble,
    Button,
    ButtonGroup,
    Calendar,
    Card,
    Carousel,
    Chart,
    Checkbox,
    Collapsible,
    Combobox,
    Command,
    ContextMenu,
    DataTable,
    DatePicker,
    Dialog,
    Direction,
    Drawer,
    DropdownMenu,
    Empty,
    Field,
    HoverCard,
    Input,
    InputGroup,
    InputOtp,
    Item,
    Kbd,
    Label,
    Marker,
    Menubar,
    Message,
    MessageScroller,
    NativeSelect,
    NavigationMenu,
    Pagination,
    Popover,
    Progress,
    RadioGroup,
    Resizable,
    ScrollArea,
    Select,
    Separator,
    Sheet,
    Sidebar,
    Skeleton,
    Slider,
    Sonner,
    Spinner,
    Switch,
    Table,
    Tabs,
    Textarea,
    Toast,
    Toggle,
    ToggleGroup,
    Tooltip,
    Typography,
}

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum UiComponentCategory {
    Action,
    Data,
    Disclosure,
    Display,
    Feedback,
    Form,
    Layout,
    Messaging,
    Navigation,
    Overlay,
    Typography,
    Utility,
}

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum FrameworkMode {
    LeptosOnly,
    SharedSpec,
}

#[derive(Debug, Clone, Copy, Deserialize, PartialEq, Eq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum UiStateModel {
    ConsumerDurable,
    Ephemeral,
    Stateless,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ComponentDefinition {
    pub id: UiComponentId,
    pub slug: &'static str,
    pub name: &'static str,
    pub summary: &'static str,
    pub category: UiComponentCategory,
    pub framework: FrameworkMode,
    pub state: UiStateModel,
}

pub const SHADCN_COMPONENT_COUNT: usize = 64;

pub const SHADCN_COMPONENTS: [ComponentDefinition; SHADCN_COMPONENT_COUNT] = [
    ComponentDefinition {
        id: UiComponentId::Accordion,
        slug: "accordion",
        name: "Accordion",
        summary: "A vertically stacked disclosure set for expanding one or more sections.",
        category: UiComponentCategory::Disclosure,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Alert,
        slug: "alert",
        name: "Alert",
        summary: "A callout that highlights status, risk, or next action.",
        category: UiComponentCategory::Feedback,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::AlertDialog,
        slug: "alert-dialog",
        name: "Alert Dialog",
        summary: "A blocking confirmation dialog for destructive or high-friction actions.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::AspectRatio,
        slug: "aspect-ratio",
        name: "Aspect Ratio",
        summary: "A fixed-ratio media frame that keeps images, canvases, and embeds stable.",
        category: UiComponentCategory::Layout,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Attachment,
        slug: "attachment",
        name: "Attachment",
        summary: "A file or resource chip shown inside message and compose surfaces.",
        category: UiComponentCategory::Messaging,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Avatar,
        slug: "avatar",
        name: "Avatar",
        summary: "A user or entity identity image with fallback initials.",
        category: UiComponentCategory::Display,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Badge,
        slug: "badge",
        name: "Badge",
        summary: "A compact status, category, or count label.",
        category: UiComponentCategory::Display,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Breadcrumb,
        slug: "breadcrumb",
        name: "Breadcrumb",
        summary: "A hierarchical location trail for route and document navigation.",
        category: UiComponentCategory::Navigation,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Bubble,
        slug: "bubble",
        name: "Bubble",
        summary: "A chat or activity message container with sender-aware alignment.",
        category: UiComponentCategory::Messaging,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Button,
        slug: "button",
        name: "Button",
        summary: "The primary action primitive for commands, links, and submit actions.",
        category: UiComponentCategory::Action,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::ButtonGroup,
        slug: "button-group",
        name: "Button Group",
        summary: "A grouped set of related actions with shared edge and focus behavior.",
        category: UiComponentCategory::Action,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Calendar,
        slug: "calendar",
        name: "Calendar",
        summary: "A date grid for single-date and range selection.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Card,
        slug: "card",
        name: "Card",
        summary: "A framed content surface with header, body, and footer slots.",
        category: UiComponentCategory::Display,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Carousel,
        slug: "carousel",
        name: "Carousel",
        summary: "A paged horizontal media or content strip with previous/next controls.",
        category: UiComponentCategory::Display,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Chart,
        slug: "chart",
        name: "Chart",
        summary: "A themed data visualization frame with legend, tooltip, and series metadata.",
        category: UiComponentCategory::Data,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Checkbox,
        slug: "checkbox",
        name: "Checkbox",
        summary: "A binary or indeterminate form control.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Collapsible,
        slug: "collapsible",
        name: "Collapsible",
        summary: "A single disclosure region that can hide or reveal content.",
        category: UiComponentCategory::Disclosure,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Combobox,
        slug: "combobox",
        name: "Combobox",
        summary: "An input-backed picker with filtering and keyboard navigation.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Command,
        slug: "command",
        name: "Command",
        summary: "A command palette for searchable actions and route jumps.",
        category: UiComponentCategory::Navigation,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::ContextMenu,
        slug: "context-menu",
        name: "Context Menu",
        summary: "A pointer-triggered menu scoped to a target region.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::DataTable,
        slug: "data-table",
        name: "Data Table",
        summary: "A sortable, filterable tabular data surface.",
        category: UiComponentCategory::Data,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::DatePicker,
        slug: "date-picker",
        name: "Date Picker",
        summary: "A composed date input, popover, and calendar selection control.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Dialog,
        slug: "dialog",
        name: "Dialog",
        summary: "A modal or non-modal overlay for focused workflows.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Direction,
        slug: "direction",
        name: "Direction",
        summary: "A direction provider for left-to-right and right-to-left composition.",
        category: UiComponentCategory::Utility,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Drawer,
        slug: "drawer",
        name: "Drawer",
        summary: "A bottom or edge-attached panel for mobile-first workflows.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::DropdownMenu,
        slug: "dropdown-menu",
        name: "Dropdown Menu",
        summary: "A trigger-attached command menu with items, groups, and submenus.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Empty,
        slug: "empty",
        name: "Empty",
        summary: "A structured empty state with optional illustration and recovery action.",
        category: UiComponentCategory::Feedback,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Field,
        slug: "field",
        name: "Field",
        summary: "A form field composition wrapper for label, control, hint, and error.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::HoverCard,
        slug: "hover-card",
        name: "Hover Card",
        summary: "A rich hover or focus preview anchored to a trigger.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Input,
        slug: "input",
        name: "Input",
        summary: "A single-line text entry control.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::InputGroup,
        slug: "input-group",
        name: "Input Group",
        summary: "A composed input with addons, buttons, and inline affordances.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::InputOtp,
        slug: "input-otp",
        name: "Input OTP",
        summary: "A grouped one-time-code input with fixed slots.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Item,
        slug: "item",
        name: "Item",
        summary: "A flexible content row with media, title, description, and actions.",
        category: UiComponentCategory::Display,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Kbd,
        slug: "kbd",
        name: "Kbd",
        summary: "A keyboard key or shortcut token.",
        category: UiComponentCategory::Display,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Label,
        slug: "label",
        name: "Label",
        summary: "Accessible text associated with a form control.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Marker,
        slug: "marker",
        name: "Marker",
        summary: "A small position, unread, or annotation marker in message surfaces.",
        category: UiComponentCategory::Messaging,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Menubar,
        slug: "menubar",
        name: "Menubar",
        summary: "A horizontal application menu with nested commands.",
        category: UiComponentCategory::Navigation,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Message,
        slug: "message",
        name: "Message",
        summary: "A durable chat or activity message with content and metadata.",
        category: UiComponentCategory::Messaging,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::MessageScroller,
        slug: "message-scroller",
        name: "Message Scroller",
        summary: "A scroll container optimized for live message history and jump-to-latest.",
        category: UiComponentCategory::Messaging,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::NativeSelect,
        slug: "native-select",
        name: "Native Select",
        summary: "A platform-native select control styled to match tokens.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::NavigationMenu,
        slug: "navigation-menu",
        name: "Navigation Menu",
        summary: "A responsive top-level navigation system with panels and links.",
        category: UiComponentCategory::Navigation,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Pagination,
        slug: "pagination",
        name: "Pagination",
        summary: "A page navigation control for collections and tables.",
        category: UiComponentCategory::Navigation,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Popover,
        slug: "popover",
        name: "Popover",
        summary: "A lightweight anchored overlay for controls and secondary content.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Progress,
        slug: "progress",
        name: "Progress",
        summary: "A determinate or indeterminate progress indicator.",
        category: UiComponentCategory::Feedback,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::RadioGroup,
        slug: "radio-group",
        name: "Radio Group",
        summary: "A mutually exclusive option group.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Resizable,
        slug: "resizable",
        name: "Resizable",
        summary: "A split panel layout with draggable handles.",
        category: UiComponentCategory::Layout,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::ScrollArea,
        slug: "scroll-area",
        name: "Scroll Area",
        summary: "A custom scroll viewport with tokenized scrollbars and fade affordances.",
        category: UiComponentCategory::Layout,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Select,
        slug: "select",
        name: "Select",
        summary: "A trigger-based listbox selection control.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Separator,
        slug: "separator",
        name: "Separator",
        summary: "A horizontal or vertical divider between related content.",
        category: UiComponentCategory::Layout,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
    ComponentDefinition {
        id: UiComponentId::Sheet,
        slug: "sheet",
        name: "Sheet",
        summary: "An edge-attached overlay panel for secondary workflows.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Sidebar,
        slug: "sidebar",
        name: "Sidebar",
        summary: "A persistent or collapsible app navigation rail.",
        category: UiComponentCategory::Navigation,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Skeleton,
        slug: "skeleton",
        name: "Skeleton",
        summary: "A loading placeholder that preserves layout shape.",
        category: UiComponentCategory::Feedback,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Slider,
        slug: "slider",
        name: "Slider",
        summary: "A range input for selecting one or more numeric values.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Sonner,
        slug: "sonner",
        name: "Sonner",
        summary: "A toast notification viewport modeled after Sonner semantics.",
        category: UiComponentCategory::Feedback,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Spinner,
        slug: "spinner",
        name: "Spinner",
        summary: "A compact activity indicator.",
        category: UiComponentCategory::Feedback,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Switch,
        slug: "switch",
        name: "Switch",
        summary: "A binary on/off control with an animated thumb.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Table,
        slug: "table",
        name: "Table",
        summary: "A semantic table for structured rows and columns.",
        category: UiComponentCategory::Data,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Tabs,
        slug: "tabs",
        name: "Tabs",
        summary: "A tabbed interface for switching panels in place.",
        category: UiComponentCategory::Navigation,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Textarea,
        slug: "textarea",
        name: "Textarea",
        summary: "A multi-line text entry control.",
        category: UiComponentCategory::Form,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Toast,
        slug: "toast",
        name: "Toast",
        summary: "A transient notification item with optional action.",
        category: UiComponentCategory::Feedback,
        framework: FrameworkMode::LeptosOnly,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Toggle,
        slug: "toggle",
        name: "Toggle",
        summary: "A pressed/unpressed button control.",
        category: UiComponentCategory::Action,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::ToggleGroup,
        slug: "toggle-group",
        name: "Toggle Group",
        summary: "A grouped single-select or multi-select toggle set.",
        category: UiComponentCategory::Action,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::ConsumerDurable,
    },
    ComponentDefinition {
        id: UiComponentId::Tooltip,
        slug: "tooltip",
        name: "Tooltip",
        summary: "A focus and hover popup that describes a control.",
        category: UiComponentCategory::Overlay,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Ephemeral,
    },
    ComponentDefinition {
        id: UiComponentId::Typography,
        slug: "typography",
        name: "Typography",
        summary: "A typographic recipe set for headings, body copy, lists, and code.",
        category: UiComponentCategory::Typography,
        framework: FrameworkMode::SharedSpec,
        state: UiStateModel::Stateless,
    },
];

impl UiComponentId {
    pub const ALL: [Self; SHADCN_COMPONENT_COUNT] = [
        Self::Accordion,
        Self::Alert,
        Self::AlertDialog,
        Self::AspectRatio,
        Self::Attachment,
        Self::Avatar,
        Self::Badge,
        Self::Breadcrumb,
        Self::Bubble,
        Self::Button,
        Self::ButtonGroup,
        Self::Calendar,
        Self::Card,
        Self::Carousel,
        Self::Chart,
        Self::Checkbox,
        Self::Collapsible,
        Self::Combobox,
        Self::Command,
        Self::ContextMenu,
        Self::DataTable,
        Self::DatePicker,
        Self::Dialog,
        Self::Direction,
        Self::Drawer,
        Self::DropdownMenu,
        Self::Empty,
        Self::Field,
        Self::HoverCard,
        Self::Input,
        Self::InputGroup,
        Self::InputOtp,
        Self::Item,
        Self::Kbd,
        Self::Label,
        Self::Marker,
        Self::Menubar,
        Self::Message,
        Self::MessageScroller,
        Self::NativeSelect,
        Self::NavigationMenu,
        Self::Pagination,
        Self::Popover,
        Self::Progress,
        Self::RadioGroup,
        Self::Resizable,
        Self::ScrollArea,
        Self::Select,
        Self::Separator,
        Self::Sheet,
        Self::Sidebar,
        Self::Skeleton,
        Self::Slider,
        Self::Sonner,
        Self::Spinner,
        Self::Switch,
        Self::Table,
        Self::Tabs,
        Self::Textarea,
        Self::Toast,
        Self::Toggle,
        Self::ToggleGroup,
        Self::Tooltip,
        Self::Typography,
    ];

    pub const fn index(self) -> usize {
        match self {
            Self::Accordion => 0,
            Self::Alert => 1,
            Self::AlertDialog => 2,
            Self::AspectRatio => 3,
            Self::Attachment => 4,
            Self::Avatar => 5,
            Self::Badge => 6,
            Self::Breadcrumb => 7,
            Self::Bubble => 8,
            Self::Button => 9,
            Self::ButtonGroup => 10,
            Self::Calendar => 11,
            Self::Card => 12,
            Self::Carousel => 13,
            Self::Chart => 14,
            Self::Checkbox => 15,
            Self::Collapsible => 16,
            Self::Combobox => 17,
            Self::Command => 18,
            Self::ContextMenu => 19,
            Self::DataTable => 20,
            Self::DatePicker => 21,
            Self::Dialog => 22,
            Self::Direction => 23,
            Self::Drawer => 24,
            Self::DropdownMenu => 25,
            Self::Empty => 26,
            Self::Field => 27,
            Self::HoverCard => 28,
            Self::Input => 29,
            Self::InputGroup => 30,
            Self::InputOtp => 31,
            Self::Item => 32,
            Self::Kbd => 33,
            Self::Label => 34,
            Self::Marker => 35,
            Self::Menubar => 36,
            Self::Message => 37,
            Self::MessageScroller => 38,
            Self::NativeSelect => 39,
            Self::NavigationMenu => 40,
            Self::Pagination => 41,
            Self::Popover => 42,
            Self::Progress => 43,
            Self::RadioGroup => 44,
            Self::Resizable => 45,
            Self::ScrollArea => 46,
            Self::Select => 47,
            Self::Separator => 48,
            Self::Sheet => 49,
            Self::Sidebar => 50,
            Self::Skeleton => 51,
            Self::Slider => 52,
            Self::Sonner => 53,
            Self::Spinner => 54,
            Self::Switch => 55,
            Self::Table => 56,
            Self::Tabs => 57,
            Self::Textarea => 58,
            Self::Toast => 59,
            Self::Toggle => 60,
            Self::ToggleGroup => 61,
            Self::Tooltip => 62,
            Self::Typography => 63,
        }
    }

    pub fn definition(self) -> &'static ComponentDefinition {
        &SHADCN_COMPONENTS[self.index()]
    }

    pub const fn anatomy_parts(self) -> &'static [&'static str] {
        match self {
            Self::Accordion => &[
                "Accordion",
                "AccordionItem",
                "AccordionTrigger",
                "AccordionContent",
            ],
            Self::Alert => &["Alert", "AlertTitle", "AlertDescription", "AlertAction"],
            Self::AlertDialog => &[
                "AlertDialog",
                "AlertDialogTrigger",
                "AlertDialogContent",
                "AlertDialogHeader",
                "AlertDialogFooter",
                "AlertDialogAction",
                "AlertDialogCancel",
            ],
            Self::AspectRatio => &["AspectRatio", "AspectRatioFrame", "AspectRatioMedia"],
            Self::Attachment => &[
                "Attachment",
                "AttachmentPreview",
                "AttachmentTitle",
                "AttachmentMeta",
                "AttachmentAction",
            ],
            Self::Avatar => &["Avatar", "AvatarImage", "AvatarFallback"],
            Self::Badge => &["Badge", "BadgeIcon", "BadgeText"],
            Self::Breadcrumb => &[
                "Breadcrumb",
                "BreadcrumbList",
                "BreadcrumbItem",
                "BreadcrumbLink",
                "BreadcrumbSeparator",
                "BreadcrumbPage",
            ],
            Self::Bubble => &[
                "Bubble",
                "BubbleAvatar",
                "BubbleContent",
                "BubbleMeta",
                "BubbleActions",
            ],
            Self::Button => &["Button", "ButtonIcon", "ButtonLabel"],
            Self::ButtonGroup => &["ButtonGroup", "ButtonGroupItem", "ButtonGroupSeparator"],
            Self::Calendar => &[
                "Calendar",
                "CalendarHeader",
                "CalendarGrid",
                "CalendarDay",
                "CalendarRange",
            ],
            Self::Card => &[
                "Card",
                "CardHeader",
                "CardTitle",
                "CardDescription",
                "CardContent",
                "CardFooter",
            ],
            Self::Carousel => &[
                "Carousel",
                "CarouselContent",
                "CarouselItem",
                "CarouselPrevious",
                "CarouselNext",
                "CarouselIndicator",
            ],
            Self::Chart => &[
                "ChartContainer",
                "ChartSeries",
                "ChartLegend",
                "ChartTooltip",
                "ChartAxis",
            ],
            Self::Checkbox => &[
                "Checkbox",
                "CheckboxIndicator",
                "CheckboxLabel",
                "CheckboxDescription",
            ],
            Self::Collapsible => &["Collapsible", "CollapsibleTrigger", "CollapsibleContent"],
            Self::Combobox => &[
                "Combobox",
                "ComboboxInput",
                "ComboboxList",
                "ComboboxOption",
                "ComboboxEmpty",
            ],
            Self::Command => &[
                "Command",
                "CommandInput",
                "CommandList",
                "CommandGroup",
                "CommandItem",
                "CommandShortcut",
            ],
            Self::ContextMenu => &[
                "ContextMenu",
                "ContextMenuTrigger",
                "ContextMenuContent",
                "ContextMenuItem",
                "ContextMenuSeparator",
                "ContextMenuSubmenu",
            ],
            Self::DataTable => &[
                "DataTable",
                "DataTableToolbar",
                "DataTableHeader",
                "DataTableRow",
                "DataTableCell",
                "DataTablePagination",
            ],
            Self::DatePicker => &[
                "DatePicker",
                "DatePickerTrigger",
                "DatePickerPopover",
                "DatePickerCalendar",
                "DatePickerValue",
            ],
            Self::Dialog => &[
                "Dialog",
                "DialogTrigger",
                "DialogContent",
                "DialogHeader",
                "DialogTitle",
                "DialogDescription",
                "DialogFooter",
            ],
            Self::Direction => &[
                "DirectionProvider",
                "DirectionScope",
                "DirectionAwareContent",
            ],
            Self::Drawer => &[
                "Drawer",
                "DrawerTrigger",
                "DrawerContent",
                "DrawerHeader",
                "DrawerFooter",
                "DrawerHandle",
            ],
            Self::DropdownMenu => &[
                "DropdownMenu",
                "DropdownMenuTrigger",
                "DropdownMenuContent",
                "DropdownMenuItem",
                "DropdownMenuLabel",
                "DropdownMenuSeparator",
            ],
            Self::Empty => &[
                "Empty",
                "EmptyHeader",
                "EmptyTitle",
                "EmptyDescription",
                "EmptyContent",
                "EmptyAction",
            ],
            Self::Field => &[
                "Field",
                "FieldLabel",
                "FieldControl",
                "FieldDescription",
                "FieldError",
            ],
            Self::HoverCard => &[
                "HoverCard",
                "HoverCardTrigger",
                "HoverCardContent",
                "HoverCardArrow",
            ],
            Self::Input => &["Input", "InputPrefix", "InputControl", "InputSuffix"],
            Self::InputGroup => &[
                "InputGroup",
                "InputGroupAddon",
                "InputGroupInput",
                "InputGroupButton",
            ],
            Self::InputOtp => &[
                "InputOtp",
                "InputOtpGroup",
                "InputOtpSlot",
                "InputOtpSeparator",
            ],
            Self::Item => &[
                "Item",
                "ItemMedia",
                "ItemContent",
                "ItemTitle",
                "ItemDescription",
                "ItemActions",
            ],
            Self::Kbd => &["Kbd", "KbdKey", "KbdChord"],
            Self::Label => &["Label", "LabelText", "LabelRequirement"],
            Self::Marker => &["Marker", "MarkerDot", "MarkerLabel", "MarkerAnchor"],
            Self::Menubar => &[
                "Menubar",
                "MenubarMenu",
                "MenubarTrigger",
                "MenubarContent",
                "MenubarItem",
            ],
            Self::Message => &[
                "Message",
                "MessageHeader",
                "MessageContent",
                "MessageFooter",
                "MessageActions",
            ],
            Self::MessageScroller => &[
                "MessageScroller",
                "MessageViewport",
                "MessageList",
                "MessageAnchor",
                "MessageJumpButton",
            ],
            Self::NativeSelect => &[
                "NativeSelect",
                "NativeSelectTrigger",
                "NativeSelectOption",
                "NativeSelectValue",
            ],
            Self::NavigationMenu => &[
                "NavigationMenu",
                "NavigationMenuList",
                "NavigationMenuItem",
                "NavigationMenuTrigger",
                "NavigationMenuContent",
                "NavigationMenuLink",
            ],
            Self::Pagination => &[
                "Pagination",
                "PaginationContent",
                "PaginationItem",
                "PaginationPrevious",
                "PaginationLink",
                "PaginationNext",
            ],
            Self::Popover => &[
                "Popover",
                "PopoverTrigger",
                "PopoverContent",
                "PopoverArrow",
            ],
            Self::Progress => &[
                "Progress",
                "ProgressTrack",
                "ProgressIndicator",
                "ProgressLabel",
            ],
            Self::RadioGroup => &[
                "RadioGroup",
                "RadioGroupItem",
                "RadioGroupIndicator",
                "RadioGroupLabel",
            ],
            Self::Resizable => &["ResizablePanelGroup", "ResizablePanel", "ResizableHandle"],
            Self::ScrollArea => &[
                "ScrollArea",
                "ScrollViewport",
                "ScrollContent",
                "ScrollBar",
                "ScrollCorner",
            ],
            Self::Select => &[
                "Select",
                "SelectTrigger",
                "SelectValue",
                "SelectContent",
                "SelectItem",
                "SelectGroup",
            ],
            Self::Separator => &["Separator", "SeparatorLine", "SeparatorLabel"],
            Self::Sheet => &[
                "Sheet",
                "SheetTrigger",
                "SheetContent",
                "SheetHeader",
                "SheetFooter",
                "SheetClose",
            ],
            Self::Sidebar => &[
                "Sidebar",
                "SidebarHeader",
                "SidebarContent",
                "SidebarGroup",
                "SidebarMenu",
                "SidebarFooter",
                "SidebarRail",
            ],
            Self::Skeleton => &["Skeleton", "SkeletonBlock", "SkeletonText", "SkeletonMedia"],
            Self::Slider => &[
                "Slider",
                "SliderTrack",
                "SliderRange",
                "SliderThumb",
                "SliderValue",
            ],
            Self::Sonner => &[
                "SonnerProvider",
                "SonnerViewport",
                "SonnerToast",
                "SonnerAction",
                "SonnerDismiss",
            ],
            Self::Spinner => &[
                "Spinner",
                "SpinnerTrack",
                "SpinnerIndicator",
                "SpinnerLabel",
            ],
            Self::Switch => &["Switch", "SwitchTrack", "SwitchThumb", "SwitchLabel"],
            Self::Table => &[
                "Table",
                "TableHeader",
                "TableBody",
                "TableRow",
                "TableHead",
                "TableCell",
                "TableCaption",
            ],
            Self::Tabs => &["Tabs", "TabsList", "TabsTrigger", "TabsContent"],
            Self::Textarea => &[
                "Textarea",
                "TextareaControl",
                "TextareaCounter",
                "TextareaHint",
            ],
            Self::Toast => &[
                "ToastProvider",
                "ToastViewport",
                "Toast",
                "ToastTitle",
                "ToastDescription",
                "ToastAction",
            ],
            Self::Toggle => &["Toggle", "ToggleIndicator", "ToggleLabel"],
            Self::ToggleGroup => &["ToggleGroup", "ToggleGroupItem", "ToggleGroupIndicator"],
            Self::Tooltip => &[
                "Tooltip",
                "TooltipTrigger",
                "TooltipContent",
                "TooltipArrow",
            ],
            Self::Typography => &[
                "Typography",
                "TypographyH1",
                "TypographyH2",
                "TypographyP",
                "TypographyList",
                "TypographyBlockquote",
            ],
        }
    }

    pub fn issue_filename(self) -> String {
        format!("{:02}-{}.md", self.index() + 1, self.definition().slug)
    }
}

impl UiComponentCategory {
    pub const fn label(self) -> &'static str {
        match self {
            Self::Action => "Action",
            Self::Data => "Data",
            Self::Disclosure => "Disclosure",
            Self::Display => "Display",
            Self::Feedback => "Feedback",
            Self::Form => "Form",
            Self::Layout => "Layout",
            Self::Messaging => "Messaging",
            Self::Navigation => "Navigation",
            Self::Overlay => "Overlay",
            Self::Typography => "Typography",
            Self::Utility => "Utility",
        }
    }
}

impl FrameworkMode {
    pub const fn label(self) -> &'static str {
        match self {
            Self::LeptosOnly => "Leptos Only",
            Self::SharedSpec => "Shared Spec",
        }
    }
}

impl UiStateModel {
    pub const fn label(self) -> &'static str {
        match self {
            Self::ConsumerDurable => "Consumer Durable",
            Self::Ephemeral => "Ephemeral",
            Self::Stateless => "Stateless",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;
    use std::path::Path;

    #[test]
    fn official_shadcn_inventory_is_currently_sixty_four_components() {
        assert_eq!(SHADCN_COMPONENTS.len(), 64);
        assert_eq!(UiComponentId::ALL.len(), SHADCN_COMPONENTS.len());
    }

    #[test]
    fn every_component_has_unique_slug_and_anatomy() {
        let mut slugs = HashSet::new();
        for id in UiComponentId::ALL {
            let definition = id.definition();
            assert!(
                slugs.insert(definition.slug),
                "duplicate slug {}",
                definition.slug
            );
            assert!(
                !id.anatomy_parts().is_empty(),
                "{} has no anatomy",
                definition.name
            );
        }
    }

    #[test]
    fn every_component_has_task_file() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../_issues/ui");
        for id in UiComponentId::ALL {
            let path = root.join(id.issue_filename());
            assert!(path.exists(), "missing {}", path.display());
        }
    }
}
