[book]
title = "rs-dean-ui"
authors = ["rs-dean"]
language = "en"
src = "src"

[build]
build-dir = "../../../target/mdbook/ui"
create-missing = false

[preprocessor.rs-dean-templates]
command = "cargo xtask mdbook-template"
after = ["links"]
